apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: hw
spec:
 rules:
   - http:
       paths:
         - path: /
           backend:
             serviceName: httpservice
             servicePort: 8088

